#!/usr/bin/env bash
# AI Recruiter Hackathon — Automated Testing Procedure Script
set -e

echo "========================================================"
echo "🧪 Starting AI Recruiter Hackathon Pipeline Verification"
echo "========================================================"

# Step 1: Run pytest fairness & security unit tests
echo ""
echo "▶️  Step 1: Running Stage A Fairness & Compliance Unit Tests..."
cd $(dirname "$0")/..
python3 -m pytest backend/tests/test_fairness.py -v

# Step 2: Test Offline Submission Pipeline (Stage 3 Sandbox Mode)
echo ""
echo "▶️  Step 2: Testing Offline Submission Pipeline (No API calls)..."
python3 hackathon/run_submission.py --candidates hackathon/data/sample_candidates.json --out hackathon/test_offline_submission.csv

# Step 3: Run Official Validator against Offline CSV
echo ""
echo "▶️  Step 3: Running Official Validator on Offline Submission..."
python3 hackathon/validate_submission.py hackathon/test_offline_submission.csv

# Step 4: Display sample results
echo ""
echo "🎉 All verification checks passed successfully!"
echo "Here are the top 3 ranked candidates generated by the pipeline:"
echo "--------------------------------------------------------"
head -n 4 hackathon/test_offline_submission.csv | column -s, -t
echo "--------------------------------------------------------"
rm -f hackathon/test_offline_submission.csv
